openapi: 3.0.0
info:
  title: TD OpenAPI Specification - Exercice 1
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Ping endpoint
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: pong