openapi: 3.0.0
info:
  title: TD OpenAPI Specification - Exercice 2
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get users with pagination
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          required: false
        - name: size
          in: query
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
              example:
                - id: 1
                  name: Alice
                  email: alice@example.com
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Bad types for provided query parameters"